version: '3'

services:
  open-genes-backend:
    build: .
    image: open_genes_backend:latest
    hostname: opengenes
    container_name: open_genes_backend
    volumes:
      - "./opengenes:/open-genes-backend/opengenes"
      - "./scripts:/open-genes-backend/scripts"
      - "./.env:/open-genes-backend/.env"
      - "./pyproject.toml:/open-genes-backend/pyproject.toml"
      - "./pdm.lock:/open-genes-backend/pdm.lock"
    network_mode: "host"
